/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IgRouteImport } from './routes/ig'
import { Route as PagosRouteImport } from './routes/pagos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as ApiCheckoutRouteImport } from './routes/api.checkout'
import { Route as ApiFxRouteImport } from './routes/api.fx'
import { Route as ApiGeoRouteImport } from './routes/api.geo'
import { Route as ApiTrackVisitRouteImport } from './routes/api.track-visit'
import { Route as ApiTrmRouteImport } from './routes/api.trm'
import { Route as ApiWompiWebhookRouteImport } from './routes/api.wompi-webhook'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IgRoute = IgRouteImport.update({
  id: '/ig',
  path: '/ig',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosRoute = PagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFxRoute = ApiFxRouteImport.update({
  id: '/api/fx',
  path: '/api/fx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoRoute = ApiGeoRouteImport.update({
  id: '/api/geo',
  path: '/api/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackVisitRoute = ApiTrackVisitRouteImport.update({
  id: '/api/track-visit',
  path: '/api/track-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrmRoute = ApiTrmRouteImport.update({
  id: '/api/trm',
  path: '/api/trm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWompiWebhookRoute = ApiWompiWebhookRouteImport.update({
  id: '/api/wompi-webhook',
  path: '/api/wompi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ig': typeof IgRoute
  '/pagos': typeof PagosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/fx': typeof ApiFxRoute
  '/api/geo': typeof ApiGeoRoute
  '/api/track-visit': typeof ApiTrackVisitRoute
  '/api/trm': typeof ApiTrmRoute
  '/api/wompi-webhook': typeof ApiWompiWebhookRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ig': typeof IgRoute
  '/pagos': typeof PagosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/fx': typeof ApiFxRoute
  '/api/geo': typeof ApiGeoRoute
  '/api/track-visit': typeof ApiTrackVisitRoute
  '/api/trm': typeof ApiTrmRoute
  '/api/wompi-webhook': typeof ApiWompiWebhookRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ig': typeof IgRoute
  '/pagos': typeof PagosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/fx': typeof ApiFxRoute
  '/api/geo': typeof ApiGeoRoute
  '/api/track-visit': typeof ApiTrackVisitRoute
  '/api/trm': typeof ApiTrmRoute
  '/api/wompi-webhook': typeof ApiWompiWebhookRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ig'
    | '/pagos'
    | '/sitemap.xml'
    | '/terminos'
    | '/api/checkout'
    | '/api/fx'
    | '/api/geo'
    | '/api/track-visit'
    | '/api/trm'
    | '/api/wompi-webhook'
    | '/producto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ig'
    | '/pagos'
    | '/sitemap.xml'
    | '/terminos'
    | '/api/checkout'
    | '/api/fx'
    | '/api/geo'
    | '/api/track-visit'
    | '/api/trm'
    | '/api/wompi-webhook'
    | '/producto/$slug'
  id:
    | '__root__'
    | '/'
    | '/ig'
    | '/pagos'
    | '/sitemap.xml'
    | '/terminos'
    | '/api/checkout'
    | '/api/fx'
    | '/api/geo'
    | '/api/track-visit'
    | '/api/trm'
    | '/api/wompi-webhook'
    | '/producto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IgRoute: typeof IgRoute
  PagosRoute: typeof PagosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminosRoute: typeof TerminosRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiFxRoute: typeof ApiFxRoute
  ApiGeoRoute: typeof ApiGeoRoute
  ApiTrackVisitRoute: typeof ApiTrackVisitRoute
  ApiTrmRoute: typeof ApiTrmRoute
  ApiWompiWebhookRoute: typeof ApiWompiWebhookRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ig': {
      id: '/ig'
      path: '/ig'
      fullPath: '/ig'
      preLoaderRoute: typeof IgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos': {
      id: '/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof PagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fx': {
      id: '/api/fx'
      path: '/api/fx'
      fullPath: '/api/fx'
      preLoaderRoute: typeof ApiFxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo': {
      id: '/api/geo'
      path: '/api/geo'
      fullPath: '/api/geo'
      preLoaderRoute: typeof ApiGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-visit': {
      id: '/api/track-visit'
      path: '/api/track-visit'
      fullPath: '/api/track-visit'
      preLoaderRoute: typeof ApiTrackVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trm': {
      id: '/api/trm'
      path: '/api/trm'
      fullPath: '/api/trm'
      preLoaderRoute: typeof ApiTrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wompi-webhook': {
      id: '/api/wompi-webhook'
      path: '/api/wompi-webhook'
      fullPath: '/api/wompi-webhook'
      preLoaderRoute: typeof ApiWompiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IgRoute: IgRoute,
  PagosRoute: PagosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminosRoute: TerminosRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiFxRoute: ApiFxRoute,
  ApiGeoRoute: ApiGeoRoute,
  ApiTrackVisitRoute: ApiTrackVisitRoute,
  ApiTrmRoute: ApiTrmRoute,
  ApiWompiWebhookRoute: ApiWompiWebhookRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
