/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PagosRouteImport } from './routes/pagos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosRoute = PagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pagos': typeof PagosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pagos': typeof PagosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pagos': typeof PagosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pagos' | '/sitemap.xml' | '/terminos' | '/producto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pagos' | '/sitemap.xml' | '/terminos' | '/producto/$slug'
  id:
    | '__root__'
    | '/'
    | '/pagos'
    | '/sitemap.xml'
    | '/terminos'
    | '/producto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagosRoute: typeof PagosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminosRoute: typeof TerminosRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos': {
      id: '/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof PagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagosRoute: PagosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminosRoute: TerminosRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
